const Post = [
  {
    name: "This way is wrong about UI Design.",
    text: "A quick guide to assisting users in the challenging steps from learning about your podcast on the web.  A quick guide to assisting users in the challenging steps from learning about your podcast on the web. ",
    btn: "READ MORE",
    time: "NOV 23 2020",
    img: "/img/postimg.png",
    category: "UI",
  },
  {
    name: "This way is wrong about UX Design.",
    text: "A quick guide to assisting users in the challenging steps from learning about your podcast on the web.  A quick guide to assisting users in the challenging steps from learning about your podcast on the web. ",
    btn: "READ MORE",
    time: "NOV 23 2020",
    img: "/img/postimg.png",
    category: "UX",
  },
  {
    name: "This way is wrong about Product Design.",
    text: "A quick guide to assisting users in the challenging steps from learning about your podcast on the web.  A quick guide to assisting users in the challenging steps from learning about your podcast on the web. ",
    btn: "READ MORE",
    time: "NOV 23 2020",
    img: "/img/postimg.png",
    category: "PD",
  },
  {
    name: "This way is wrong about UX Design.",
    text: "A quick guide to assisting users in the challenging steps from learning about your podcast on the web.  A quick guide to assisting users in the challenging steps from learning about your podcast on the web. ",
    btn: "READ MORE",
    time: "NOV 23 2020",
    img: "/img/postimg.png",
    category: "UX",
  },
  {
    name: "This way is wrong about UI Design.",
    text: "A quick guide to assisting users in the challenging steps from learning about your podcast on the web.  A quick guide to assisting users in the challenging steps from learning about your podcast on the web. ",
    btn: "READ MORE",
    time: "NOV 23 2020",
    img: "/img/postimg.png",
    category: "UI",
  },
  {
    name: "This way is wrong about UI Design.",
    text: "A quick guide to assisting users in the challenging steps from learning about your podcast on the web.  A quick guide to assisting users in the challenging steps from learning about your podcast on the web. ",
    btn: "READ MORE",
    time: "NOV 23 2020",
    img: "/img/postimg.png",
    category: "UI",
  },
];
export default Post;
